// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rfi_detail_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$RfiDetailModelImpl _$$RfiDetailModelImplFromJson(Map<String, dynamic> json) =>
    _$RfiDetailModelImpl(
      id: (json['id'] as num?)?.toInt(),
      rfiId: json['rfi_Id'] as String?,
      project: json['project'] as String?,
      work: json['work'] as String?,
      contract: json['contract'] as String?,
      structureType: json['structureType'] as String?,
      structure: json['structure'] as String?,
      component: json['component'] as String?,
      element: json['element'] as String?,
      activity: json['activity'] as String?,
      p6ActivityId: json['p6ActivityId'] as String?,
      pmisCalcFk: json['pmisCalcFk'] as String?,
      reasonForDelete: json['reasonForDelete'] as String?,
      rfiDescription: json['rfiDescription'] as String?,
      action: json['action'] as String?,
      typeOfRFI: json['typeOfRFI'] as String?,
      nameOfRepresentative: json['nameOfRepresentative'] as String?,
      enclosures: json['enclosures'] as String?,
      location: json['location'] as String?,
      description: json['description'] as String?,
      timeOfInspection: json['timeOfInspection'] as String?,
      dateOfSubmission: json['dateOfSubmission'] as String?,
      dateOfInspection: json['dateOfInspection'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      createdBy: json['createdBy'] as String?,
      emailUser: json['emailUser'] as String?,
      status: json['status'] as String?,
      assignedPersonClient: json['assignedPersonClient'] as String?,
      clientDepartment: json['clientDepartment'] as String?,
      txnId: json['txn_id'] as String?,
      assignedPersonContractor: json['assignedPersonContractor'] as String?,
      assignedPersonUserId: json['assignedPersonUserId'] as String?,
      contractId: json['contractId'] as String?,
      dyHodUserId: json['dyHodUserId'] as String?,
      rfiValidation: json['rfiValidation'] as String?,
      checklistItems: json['checklistItems'] as List<dynamic>?,
      enclosure: json['enclosure'] as List<dynamic>?,
      measurements: json['measurements'] == null
          ? null
          : MeasurementModel.fromJson(
              json['measurements'] as Map<String, dynamic>,
            ),
      contractorSubmittedDate: json['contractor_submitted_date'] as String?,
      engineerSubmittedDate: json['engineer_submitted_date'] as String?,
      contractorEsignDone: json['contractorEsignDone'] as bool?,
      engineerEsignDone: json['engineerEsignDone'] as bool?,
      closedDate: json['closedDate'] as String?,
      isDeleted: json['isDeleted'] as bool?,
      deletedAt: json['deletedAt'] as String?,
      attachments: json['attachments'] as List<dynamic>?,
      estatus: json['estatus'] as String?,
      enclosuresList: (json['enclosuresList'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
    );

Map<String, dynamic> _$$RfiDetailModelImplToJson(
  _$RfiDetailModelImpl instance,
) => <String, dynamic>{
  'id': instance.id,
  'rfi_Id': instance.rfiId,
  'project': instance.project,
  'work': instance.work,
  'contract': instance.contract,
  'structureType': instance.structureType,
  'structure': instance.structure,
  'component': instance.component,
  'element': instance.element,
  'activity': instance.activity,
  'p6ActivityId': instance.p6ActivityId,
  'pmisCalcFk': instance.pmisCalcFk,
  'reasonForDelete': instance.reasonForDelete,
  'rfiDescription': instance.rfiDescription,
  'action': instance.action,
  'typeOfRFI': instance.typeOfRFI,
  'nameOfRepresentative': instance.nameOfRepresentative,
  'enclosures': instance.enclosures,
  'location': instance.location,
  'description': instance.description,
  'timeOfInspection': instance.timeOfInspection,
  'dateOfSubmission': instance.dateOfSubmission,
  'dateOfInspection': instance.dateOfInspection,
  'createdAt': instance.createdAt,
  'updatedAt': instance.updatedAt,
  'createdBy': instance.createdBy,
  'emailUser': instance.emailUser,
  'status': instance.status,
  'assignedPersonClient': instance.assignedPersonClient,
  'clientDepartment': instance.clientDepartment,
  'txn_id': instance.txnId,
  'assignedPersonContractor': instance.assignedPersonContractor,
  'assignedPersonUserId': instance.assignedPersonUserId,
  'contractId': instance.contractId,
  'dyHodUserId': instance.dyHodUserId,
  'rfiValidation': instance.rfiValidation,
  'checklistItems': instance.checklistItems,
  'enclosure': instance.enclosure,
  'measurements': instance.measurements,
  'contractor_submitted_date': instance.contractorSubmittedDate,
  'engineer_submitted_date': instance.engineerSubmittedDate,
  'contractorEsignDone': instance.contractorEsignDone,
  'engineerEsignDone': instance.engineerEsignDone,
  'closedDate': instance.closedDate,
  'isDeleted': instance.isDeleted,
  'deletedAt': instance.deletedAt,
  'attachments': instance.attachments,
  'estatus': instance.estatus,
  'enclosuresList': instance.enclosuresList,
};

_$MeasurementModelImpl _$$MeasurementModelImplFromJson(
  Map<String, dynamic> json,
) => _$MeasurementModelImpl(
  id: (json['id'] as num?)?.toInt(),
  measurementType: json['measurementType'] as String?,
  length: json['length'],
  breadth: json['breadth'],
  height: json['height'],
  weight: json['weight'],
  units: json['units'] as String?,
  noOfItems: (json['noOfItems'] as num?)?.toInt(),
  totalQty: json['totalQty'],
  l: json['l'],
  b: json['b'],
  h: json['h'],
  no: (json['no'] as num?)?.toInt(),
);

Map<String, dynamic> _$$MeasurementModelImplToJson(
  _$MeasurementModelImpl instance,
) => <String, dynamic>{
  'id': instance.id,
  'measurementType': instance.measurementType,
  'length': instance.length,
  'breadth': instance.breadth,
  'height': instance.height,
  'weight': instance.weight,
  'units': instance.units,
  'noOfItems': instance.noOfItems,
  'totalQty': instance.totalQty,
  'l': instance.l,
  'b': instance.b,
  'h': instance.h,
  'no': instance.no,
};
